### ISSUE TITLE
Support top level class block

### ISSUE THREAD

**Issue by tpluscode** [zazuko/api-testing-dsl#1]
## Intro

To test resources, we need to be able to distinguish their shapes. Hydra and SIREN both come with a term `Class`, which we could use a common denominator for a "type of resource".

## DSL snippet

```
With Class http://schema.org/Person {
}
```

### Details

Note that the class id does not have to be a URI. Any string should be acceptable. No whitespace for now

## Generated JSON

This should translate to a root level Class step

```json
{
  "steps": [{
    "type": "Class",
    "classId": "http://schema.org/Person"
  }]
}
```

**Comment by mchlrch** [comment]
On the DSL side, I used the default `STRING` terminal rule from Xtext for the *name/id* instead of defining a custom terminal rule:

```
With Class "http://schema.org/Person" {
}
```
generates ..
```
{
	"steps": [
		{
			"type": "Class",
			"classId": "http://schema.org/Person",
			"children": [
			]
		}
	]
}
```

**Comment by tpluscode** [comment]
> On the DSL side, I used the default STRING terminal rule from Xtext for the name/id instead of defining a custom terminal rule:

I don't understand what that means :)

**Comment by mchlrch** [comment]
Xtext ships some commonly used terminals [1] and our language is using these [2]. This is pragmatic and we can change once we need/want to.

The effect of using `STRING` for the name/id is that the name/id is in double-quotes and just a string without constraints on the content. This is maybe not what we want in the long run but good to get started. It allows us to play with both simple and URI identifiers. For URI identifiers, we would otherwise need to define a custom terminal instead. Once we need identifiers that are cross-referenceable, we will come back to this.

1: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/src/org/eclipse/xtext/common/Terminals.xtext
2: https://github.com/zazuko/api-testing-dsl/blob/master/com.zazuko.apitesting.dsl/com.zazuko.apitesting.dsl/src/com/zazuko/apitesting/dsl/ApiTestingDsl.xtext#L1
